spring.application.name=api-gateway
server.port=8080

spring.cloud.gateway.server.webflux.routes[0].id=patient-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/pacientes/**

spring.cloud.gateway.server.webflux.routes[1].id=doctor-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/doctores/**



eureka.client.service-url.default-zone=http://eureka:password@localhost:8761/eureka
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
logging.pattern.level= %5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]