spring.application.name=doctor-service
server.port=8082

spring.datasource.url=jdbc:mariadb://localhost:3306/doctor?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1469370
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Eureka Client
eureka.client.service-url.default-zone=http://eureka:password@localhost:8761/eureka
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
logging.pattern.level= %5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]